package com.test.org.Automation_Practice_2;

import java.io.FileNotFoundException;

public class try_catch {
	
	public static void main (String[] args)
	{
		
		try {
			
			System.out.println("Thats a try block");	
		
		} 
		
		catch (Exception e) {
			
			System.out.println("Thats a catch block");
		}
		
		
		finally {
			System.out.println("Finally Block");
		}
		
		
		
	}

}
